# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '\u4f18\u5b9c\u5de7\u8d2d\u7528\u6237', 'verbose_name_plural': '\u4f18\u5b9c\u5de7\u8d2d\u7528\u6237'},
        ),
        migrations.AlterField(
            model_name='member',
            name='serial',
            field=models.CharField(db_index=True, default='01001000', max_length=32, null=True, verbose_name='\u5e8f\u5217\u53f7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(verbose_name='\u8ba2\u5355\u603b\u91d1\u989d'),
        ),
    ]
