# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171214_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('month', models.CharField(max_length=16, verbose_name='\u6708\u5ea6')),
                ('buyer_id', models.CharField(max_length=32, verbose_name='\u4e70\u5bb6ID')),
                ('buyer_name', models.CharField(max_length=32, verbose_name='\u4e70\u5bb6\u540d')),
                ('total', models.FloatField(verbose_name='\u8ba2\u5355\u603b\u91d1\u989d')),
                ('amount', models.IntegerField(verbose_name='\u4f18\u5b9c\u5de7\u8d2d\u6708\u5ea6\u8ba2\u5355\u6570')),
            ],
            options={
                'verbose_name': '\u5de7\u8d2d\u7528\u6237\u6708\u5ea6\u8ba2\u5355\u6c47\u603b',
                'verbose_name_plural': '\u5de7\u8d2d\u7528\u6237\u6708\u5ea6\u8ba2\u5355\u6c47\u603b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthlydata',
            unique_together=set([('month', 'buyer_id')]),
        ),
    ]
