# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_added_Monthly_Data_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='serial_history',
            field=models.TextField(default='=>', verbose_name='\u5e8f\u5217\u53f7\u6539\u53d8\u5386\u53f2'),
        ),
    ]
