# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_serial_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='moblie',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
